### ISSUE TITLE
Fix build - remove gradle errors from log

### ISSUE THREAD

**Issue by mikolevy** [autyzm-pg/friendly-plans#101]
Currently when building the app there are lots of gradle errors/warnings in build log (when building locally as well as on CI). Part of log:

Error:warning: Ignoring InnerClasses attribute for an anonymous inner class (freemarker.cache.FileTemplateLoader$1) that doesn't come with an associated EnclosingMethod attribute. This class was probably produced by a compiler that did not target the modern .class file format. The recommended solution is to recompile the class from source, using an up-to-date compiler and without specifying any "-target" type options. The consequence of ignoring this warning is that reflective operations on this class will incorrectly indicate that it is *not* an inner class.

The issue is to figure out a solution and apply it (probably update a build config)

**Comment by mgruca** [comment]
How badly do we need this: compile('de.greenrobot:DaoGenerator:1.3.0')
It's the only dependency linking to freemarker. gradlew clean build runs fine without it

**Comment by malsolec** [comment]
Hah seems we do not need this. It is building and working, schema is able to be rebuilt. I have no idea where it has been taken from. :)

I have only problem `E/EGL_emulation: tid 3599: eglSurfaceAttrib(1146): error 0x3009 (EGL_BAD_MATCH` but I think it is related to emulator not greendao.

**Comment by mgruca** [comment]
@Artem3 correct me but you were introducing DAO? Can you advise if there is reason behind generator? Can I just remove it?

**Comment by malsolec** [comment]
Yes, I removed it, and it worked. I think, I were the person who put it there. It has been taken from one of tutorials.
