### ISSUE TITLE
Task creation screen - add validation to fields

### ISSUE THREAD

**Issue by malsolec** [autyzm-pg/friendly-plans#108]
Add content validations to fields. 
- task name input field - check if task name already exists, yes -> highlight it to red, add info below
- task duration time - only numbers available -> check if it is number, highlight it to red, or green

On click next button add warning that fields are invalid and do not add task to db.

**Comment by Artem3** [comment]
@malsolec / @mikolevy  What fields are mandatory when you create task ? 
Looking at TaskTemplateRepository.java , I can assume that Name and DurationTime , right ?

**Comment by malsolec** [comment]
Name only, Duration time is optional.
