### ISSUE TITLE
List of steps assigned to task - Get steps from db

### ISSUE THREAD

**Issue by malsolec** [autyzm-pg/friendly-plans#129]
- Create repository for getting tasks, test
- Get all tasks from db for specific task

**Comment by akshitgrover** [comment]
Can I work on this? @malsolec

**Comment by malsolec** [comment]
@akshitgrover Sorry I just finished working it, but maybe try this one : https://github.com/autyzm-pg/friendly-plans/issues/144 (only for already existing views) or https://github.com/autyzm-pg/friendly-plans/issues/136 as a beginning ?
