### ISSUE TITLE
Create step - Create java fragment

### ISSUE THREAD

**Issue by malsolec** [autyzm-pg/friendly-plans#130]
- Bind fields with view
- Mock buttons actions - eg. log event to console ( e.g take all values from fields and log it on button save click")
- Activity test for the view

**Comment by mikolevy** [comment]
In this task use Data Binding: https://developer.android.com/topic/libraries/data-binding/index.html

Example of usage Data Binding with buttons is in MainActivity

**Comment by malsolec** [comment]
Resolved
