### ISSUE TITLE
Create step - Add mini picture to step creation

### ISSUE THREAD

**Issue by malsolec** [autyzm-pg/friendly-plans#134]
Display mini picture instead of picture name.

**Comment by Artem3** [comment]
this what I have for today: 

![preview](https://cloud.githubusercontent.com/assets/12259400/26823451/fd01e206-4aad-11e7-806d-01b2e9612e93.png)

**Comment by malsolec** [comment]
@Artem3 looks great, but it's different task  #136 , create step is still valid if only we will provide create step view.
