### ISSUE TITLE
Next slide button pressed by mistake

### ISSUE THREAD

**Issue by wnadurski** [autyzm-pg/friendly-plans#15]
# **ENG**:
### **Actual**:

TODO
### **Expected**:

TODO
# **PL:**
### **Stan obecny:**

Przy przechodzeniu do następnego slajdu można łatwo przycisnąć przycisk przejścia dwukrotnie przez pomyłkę, przez co od razu przechodzi się o kilka slajdów więcej.
### **Stan oczekiwany:**.

Po przejściu do nowego slajdu, przycisk przejścia przez krótki czas jest zablokowany

**Comment by malsolec** [comment]
Bug in version one. Due to version 2 will be a new app, this is no longer valid.
