### ISSUE TITLE
Safety copy of activity plan

### ISSUE THREAD

**Issue by wnadurski** [autyzm-pg/friendly-plans#16]
# **ENG**:
### **Actual**:

TODO
### **Expected**:

TODO
# **PL:**
## 
### **Stan oczekiwany:**.

Możliwość wykonania kopii zapasowej planu aktywności. Opcjonalnie: kopiowanie razem z załadowanymi obrazkami.

**Comment by autyzm-pg** [comment]
https://github.com/autyzm-pg/friendly-plans-link/i
