### ISSUE TITLE
Q: Are the components in pause activity different than in a normal activity?

### ISSUE THREAD

**Issue by magasol** [autyzm-pg/friendly-plans#221]

**Comment by malsolec** [comment]
Pause tasks have same properties, like times, sound, picture etc. but they are marked as a break task and can be performed only in situation if the child choose break action. They can have steps also, but it's not required. There is set of break tasks per one plan that are randomly chosen for the child, when the pause is started. The newer version will provide function that depending on configuration the will be subset of tasks to choose, I described it in  #222.

**Comment by malsolec** [comment]
Moved to wiki, https://github.com/autyzm-pg/friendly-plans/wiki/UX-questions for any need of discussion this issue can be reopen.
