### ISSUE TITLE
Q: Does the child decide when to make a break?

### ISSUE THREAD

**Issue by magasol** [autyzm-pg/friendly-plans#222]

**Comment by malsolec** [comment]
As far as I know child can choose a break in any moment between executing tasks. It's available from the tasks list. The break is another task that is some kind of reward for the achieved goal but it is performed the same way as task -> with instruction. In the new version there will be a set of break tasks that are available to be chosen by the child if only he/she is starting a break. For each plan breaks are assigned. The number of break tasks can be bigger then number available to choose. The subset should be random - to avoid the same breaks showing up all the time. The size of the subset is defined by therapist based on the advanced level. Children have sometimes problem with deciding and they should have too much to choose.

**Comment by malsolec** [comment]
Moved to wiki, https://github.com/autyzm-pg/friendly-plans/wiki/UX-questions for any need of discussion this issue can be reopen.
