### ISSUE TITLE
Add child - Create xml mock and empty fragment

### ISSUE THREAD

**Issue by paulamoller** [autyzm-pg/friendly-plans#245]
- Create xml for add child 
- Add empty fragment to allow to display xml on app

https://app.moqups.com/mikolevy2/tGR3mQdS/view/page/a8947aa14

**Comment by malsolec** [comment]
This mockup  shows 2 screens for add and set active, but I think it could be just one with all these function. Select active could be done on the list with all children profiles from db. I think there is not need to separate it, as it won't be used so often. @mikolevy could we update the mock ?

**Comment by malsolec** [comment]
Resolved.
