### ISSUE TITLE
Return to previous plan activity in slide mode error

### ISSUE THREAD

**Issue by malsolec** [autyzm-pg/friendly-plans#26]
# **ENG**:
### **Actual**:

TODO
### **Expected**:

TODO
# **PL:**
### **Stan obecny:**
1. Wyświetlanie w trybie slajdów
2. Przechodzenie po aktywnościach.
3. Powrót do aktywności typu galeria aktywności poprzez wybranie strzałki powrotu powoduje błąd aplikacji (crash)
### **Stan oczekiwany:**.

 Powrót do poprzedniej aktywności.

**Comment by mikolevy** [comment]
Podobny problem występuje w wypadku gdy mamy jedną aktywność w trybie slajdów. Jeżeli aktywności jest więcej to będąc na pierwszym slajdzie nie widzimy strzałki wstecz. W wypadku gdy jest tylko jedna aktywność, przycisk wstecz jest aktywny, a jego naciśnięcie powoduje crash aplikacji.
