### ISSUE TITLE
Create task: Timer should be optional

### ISSUE THREAD

**Issue by malsolec** [autyzm-pg/friendly-plans#268]
When creating or editing task adding timer time should be optional (but still should be validated if is valid digit). If timer is empty the value should be set to null.

**Comment by JanBan** [comment]
@malsolec 
Ad1, no, I did not, thanks for pointing that one out :) 
Unfortunately, though, _./gradlew build_ seems to be failing. It may be an issue with some dependencies in the project, as I am reading on some similar issues people were having. Interestingly, though, the project builds just fine in Android Studio.
Enclosing a screen from console + the whole Build Scan from Gradle. Perhaps someone has an idea?

![image](https://user-images.githubusercontent.com/32238789/39844409-3a5d2a38-53f0-11e8-9551-055bb4074b18.png)
https://scans.gradle.com/s/k4e5xsbeadrc2

As to point 2, I thought about that approach but discarded it as I also believe it wouldn't be so elegant. Tried to make it work in some other way.

I've pushed the slight changes I've made so far onto the newly-created branch, as asked. https://github.com/JanBan/friendly-plans/tree/268-Create-task-Making-timer-optional
Unfortunately, it still results in mysterious "NOT NULL" constraint violation, but I hope it is due to the database schema not being updated yet.

Thanks for your help so far :)

**Comment by mrwrob** [comment]
Did you check if it work on clean device, where FriendlyPlans were not installed? It seems that during deployment database is not recreated. When I forced to drop all tables and then created them, everything works fine (maybe not everything, but well enough). My dirty workaround:

```
diff --git a/Friendly-plans/app/src/main/java/database/repository/DaoSessionModule.java b/Friendly-plans/app/src/main/java/database/repository/DaoSessionModule.java
index b73c7ed..ff68047 100644
--- a/Friendly-plans/app/src/main/java/database/repository/DaoSessionModule.java
+++ b/Friendly-plans/app/src/main/java/database/repository/DaoSessionModule.java
@@ -23,6 +23,8 @@ public class DaoSessionModule {
                 FRIENDLY_PLANS_DB_NAME);
         Database db = helper.getWritableDb();
         daoSession = new DaoMaster(db).newSession();
+        DaoMaster.dropAllTables(db, true);
+        DaoMaster.createAllTables(db, true);
     }
 
     @Provides
diff --git a/Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/view/task_list/TaskRecyclerViewAdapter.java b/Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/view/task_list/TaskRecyclerViewAdapt
index 148dd66..3e50b6c 100644
--- a/Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/view/task_list/TaskRecyclerViewAdapter.java
+++ b/Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/view/task_list/TaskRecyclerViewAdapter.java
@@ -58,7 +58,7 @@ public class TaskRecyclerViewAdapter
     }
 
     private void setDurationTime(TaskListViewHolder holder, TaskTemplate taskItem) {
-        if (taskItem.getDurationTime() != 0) {
+        if ((taskItem.getDurationTime() != null) && (taskItem.getDurationTime() != 0)) {
             holder.taskDurationIcon.setImageResource(ICON_PLACEHOLDER_TIME_ID);
             holder.taskDurationTime.setText(String.valueOf(taskItem.getDurationTime()));
             holder.taskDurationIcon.setVisibility(View.VISIBLE);

```

After first run, you have to remove dropping and creating lines.

**Comment by JanBan** [comment]
@mrwrob , you are right, after simply whipping the device's memory and deploying app once again it actually sorts of work, thanks :) That's actually just 2 clicks and literally few seconds of waiting, so I will stick to that as a workaround as for now, and investigate why the task doesn't show up yet.

**Comment by malsolec** [comment]
That's great you have found the solution. 👍 My guess is, the problem exists because we do not support migrations at the moment. And in my opinion this is expected behaviour at the moment. Every change to database makes conflict between versions - ( database has to be dropped to apply new schema) After we will go life with the app every change to database should be done with new migration ( sql script that will update schema and records) - otherwise users will need to reinstall app and loose all their data what we really don’t want to.  Possible implementation https://piercezaifman.com/how-to-setup-database-migrations-with-greendao/. I think before going life with the app it’s not so much required, because so many migration will make the schema definition less clearer, also writing migration scripts could be complicated sometimes. But if you want, you could try implementing migration process into app, it will be required in the future.

**Comment by JanBan** [comment]
@malsolec maybe when I'll get a better grasp on everything :P

As for now, I believe I might have a working solution to the task duration issue.
https://github.com/JanBan/friendly-plans/tree/268-Create-task-Making-timer-optional

It passes all the tests, despite the one that I changed as it is obsolete (whenAddingNewTaskAndDurationIsEmptyExpectWarning => whenAddingNewTaskWithoutDurationExpectTaskToBeAddedWithoutDuration, see my last commit).

I am not sure though if I should open a pull request immediately or don't bother yet and have it pre-checked before, as it is my first contribution and I expect many suggestions.

**Comment by malsolec** [comment]
@JanBan Sure, no problem. 

If one test is not valid with new requirements it should be removed. ;) Then update your branch with current master and open PR, when all checks will pass, somebody will review it. Do not worry about suggestions it is completely normal, that is what code review was invented for. ;)

**Comment by JanBan** [comment]
@malsolec Sure, I do not worry at all, I hope for them to come as I hope to learn as much as I can :)
PR is now open.
