### ISSUE TITLE
Create plan, list of tasks - create xml mock and empty fragment

### ISSUE THREAD

**Issue by paulamoller** [autyzm-pg/friendly-plans#274]
- Create xml for list of tasks assigned to plan
- Add empty fragment to allow to display xml on app
https://app.moqups.com/mikolevy2/tGR3mQdS/view/page/a39ae0b14 (similar to the list of steps or tasks)

**Comment by msolecka** [comment]
Resolved.

**Comment by malsolec** [comment]
Done.
