### ISSUE TITLE
List of plans: After updating plan going back to list does not show updated plan

### ISSUE THREAD

**Issue by malsolec** [autyzm-pg/friendly-plans#300]
The issue exists when following these steps: 
1) From plan's list one plan is chosen to edit. 
2) The plan's view is open, and updated plan is saved. 
3) Then when button is clicked back and the list is displayed again the old plan name is still on the list. (After going back to main menu and open list again it is fine).

**Comment by mrwrob** [comment]
The same problem occurs when the Task name is modified.

**Comment by JanBan** [comment]
@mrwrob I believe with Tasks it is even worse- the Task doesn't seem to be updated at all after clicking "Save". There is no event listener on "Save" button, as far as I can tell. 
There is "eventSaveAndFinish(...)", but it's set only to the "Save and finish" button, as it closes the edit window as well.

@malsolec, should I try to fix it and create the proper listener, or in this case create new Issue, as you suggested during the latest Hangouts call to mrwrob?

**Comment by malsolec** [comment]
@JanBan Thanks for checking that. I think It will be easier to code and review it in separated PR. BTW  If you find any possible bug (even minor), and you're still not sure if it is bug or not, create issue anyway, the issue could be always closed but with pointing it we can be sure we won't miss anything important.

**Comment by JanBan** [comment]
@malsolec, honestly, I believe that the "Save" button in Plan Create does not work as well. As long as I am testing it correctly. Adding an issue than.

**Comment by mrwrob** [comment]
I believe that all that *MenuFragments are dummy and they do nothing.

**Comment by malsolec** [comment]
Yes, the items in menu were for placeholders purpose for wizard view to navigate user, like on picture below. it should not allow for any action. 
![image](https://user-images.githubusercontent.com/6892674/41472760-af8ac6ce-70b7-11e8-8411-d864f7b3a15f.png)

It does not look nice at the moment there is issue to implement it. Please check it: https://github.com/autyzm-pg/friendly-plans/issues/144 

Sorry I didn't get that you were talking about menu items.

**Comment by JanBan** [comment]
Oh, I see @mrwrob @malsolec. That would explain a lot. Whats the deal about the "Save" button, though? It's not a stage of task creation, as far as I understand. 
![image](https://user-images.githubusercontent.com/32238789/41481075-f0b4b8d0-70d0-11e8-90aa-a9fd8fd84b14.png)
I don't get when exactly would it be highlighted, wouldn't it be a button anyways, but maybe should be in the lower corner or something?

**Comment by malsolec** [comment]
@JanBan The intention of that element was that with your are on this step you get the summary of the task you have created to final complete the process. But I think now it is not really needed and this one could be removed.

I think in the left menu there should be informations about where you are in the process, what task your are creating steps for/ what plan are your selecting tasks for/ what user is currently set etc. and what is left to do. We really hoped that UX will help us how to organise it. Maybe Paulina will propose something in her new mock or you can try to think about it and we will discuss it. For that moment you don't need to worry much about this button.

**Comment by JanBan** [comment]
@malsolec, okay, got it, I will close the issue then.
