### ISSUE TITLE
Create plan, select prizes - display list of all prizes 

### ISSUE THREAD

**Issue by paulamoller** [autyzm-pg/friendly-plans#346]
- Add button to select prizes to add to the plan (in this view https://preview.uxpin.com/dc276af793ed5a347736f473bdabe8c5112f8983#/pages/87956754/simulate/sitemap?mode=i)
- Display list of prizes (in this view https://preview.uxpin.com/dc276af793ed5a347736f473bdabe8c5112f8983#/pages/87956802/simulate/sitemap?mode=i)
- Add prize to the plan after clicking on the position

**Comment by malsolec** [comment]
Resolved.
