### ISSUE TITLE
Adding pictures to application

### ISSUE THREAD

**Issue by malsolec** [autyzm-pg/friendly-plans#4]
# **ENG**:

TODO
# **PL:**
### **Stan obecny:**

Czasami nie można wyszukać niektórych obrazków i przez to załadować ich do aplikacji.
### **Stan oczekiwany:**

Powinna być możliwość ładowania do aplikacji wszystkich obrazków.

**Comment by wnadurski** [comment]
Nie można załadować obrazków innych niż te z rozszerzeniem ".JPG" (uppercase)
