### ISSUE TITLE
Add project description for new contributors

### ISSUE THREAD

**Issue by autyzm-pg** [autyzm-pg/friendly-plans#45]
# **ENG**:
### **Actual**:

There is some general info in README and CONTRIBUTING files. 
### **Expected**:

There are wiki pages with info describing project purpose and it's relationship with others applications. All info needed for conscious start of project development is included (in English).
# **PL:**
### **Stan obecny:**

W plikach README oraz CONTRIBUTING zawarte są ogólne, podstawowe informacje dotyczące projektu.
### **Stan oczekiwany:**.

Na stronach wiki oraz we wcześniej wymienionych plikach znajduje się opis celu projektu oraz związku aplikacji z pozostałymi z rodziny. Opis ten zawiera wszystkie informacje potrzebne do świadomego zaangażowania się w projekt. Informacje dostępne są w języku angielskim.

**Comment by Stefan-Mitic** [comment]
Hi @autyzm-pg I am looking to contribute to this issue, would you like me to add a general description of the project on the readme file and edit the contributing file?

**Comment by mikolevy** [comment]
Hi @Stefan-Mitic ! Of course - if You'd like to add some info to readme and contributing files and make pr with changes - it would be great! To fully resolve this issue some wiki pages are needed - describing project purpose and informations needed for start project development (e.g. basic draft of project architecture and where to find info about used libraries and so on) - but every help is welcome :)

**Comment by malsolec** [comment]
Resolved.
