### ISSUE TITLE
Add new architecture model

### ISSUE THREAD

**Issue by autyzm-pg** [autyzm-pg/friendly-plans#48]
# **ENG**:
### **Actual**:

The architecture model is incomplete and outdated (has been done for first app version).
### **Expected**:

Architecture model of new app version.
# **PL:**
### **Stan obecny:**

Model architektury jest niekompletny i nieaktualny (dotyczy pierwszej wersji aplikacji).
### **Stan oczekiwany:**.

Należy przygotować model architektury dla drugiej wersji aplikacji.

**Comment by malsolec** [comment]
Resolved.
