### ISSUE TITLE
Code style formatting

### ISSUE THREAD

**Issue by malsolec** [autyzm-pg/friendly-plans#56]
Prepare Code style settings to Android Studio: https://www.jetbrains.com/help/idea/2016.2/copying-code-style-settings.html based on the guideline: https://google.github.io/styleguide/javaguide.html

**Comment by mikolevy** [comment]
And add to wiki:

I think we should change all names (attributes, relations) so that they fit snake_case. I'd like to propose such conventions:
Database: snake_case
Android (class): PascalCase
Android (field, method): camelCase

**Comment by mikolevy** [comment]
Note about naming convention, guidelines - this part of task has been moved to separated issue: #82
