### ISSUE TITLE
Meeting notes

### ISSUE THREAD

**Issue by DragoonAethis** [autyzm-pg/friendly-plans#59]
New UI mocks, notes from the meeting with therapists, etc...?

**Comment by mikolevy** [comment]
UI mocks: https://classic.moqups.com/mikolevy/rvDDG1J9/p:aa26d9cf5
Notes from meeting with therapist in the attachment. 
[friendly-plans-req.txt](https://github.com/autyzm-pg/friendly-plans/files/613903/friendly-plans-req.txt)
