### ISSUE TITLE
Task creation screen - Display result of adding action

### ISSUE THREAD

**Issue by mikolevy** [autyzm-pg/friendly-plans#74]

**Comment by Artem3** [comment]
I believe this a good place to think about something that calls "notification manager" - How manage all the messages for a user from our app. Or I do task more complicated !? How do you think. ?

**Comment by mikolevy** [comment]
Maybe we can use toasts for it? 
https://developer.android.com/guide/topics/ui/notifiers/toasts.html
It should be simple then. But of course because we will have many different notifications (toasts) in app, building an Util class (such notification manager - as you say) sounds like a good idea. It can handle repeatable part of preparing and displaying such toast and e.g. expose a method notifyWithToast(toastText: String)

**Comment by mgruca** [comment]
you want just a simple info on bottom of screen "_Task has been created_" ?

**Comment by msolecka** [comment]
Yes, toast should be enough. :)

**Comment by malsolec** [comment]
Yes, toast should be enough. :)
