### ISSUE TITLE
Prepare tasks proposal for milestone 2

### ISSUE THREAD

**Issue by autyzm-pg** [autyzm-pg/friendly-plans#98]

**Comment by mikolevy** [comment]
Step creation:
- Create step - Create xml mock and empty fragment
- Create step - Create java fragment
-> bind fields
-> add navigation to/from
- Create step - Add step with name to db
- Create step - Add picture to step and save it to db
- Create step - Add sound to step and save it to db
- Show mini picture during step creation
- Show mini picture on steps in task list
- Show mini picture during task creation
- Enable "play sound" button during step creation
- Enable "play sound" button on steps in task list
- Enable "play sound" button during task creation
- Display step list on the screen - fetch all steps for task from db
- Display step list on the screen - create xml mock of screen and empty fragment
- Show Task's creation summary screen
- Show navigation menu - highlight where you are
- Show navigation menu - handle navigation on click
- Use different pickers for picture and sound

**Comment by mikolevy** [comment]
Add data binding

**Comment by malsolec** [comment]
Great, I will prepare issues from this list.

**Comment by mikolevy** [comment]
Cool :) I've added some issues as well - could you review current milestone 2 issues list? Do you think it's enough? :)
